### ISSUE TITLE
[Issue] For 0.1.0

### ISSUE THREAD

**Issue by CoolLKKPS** [MasterAli2/TeleportDecline#2]
1. in main menu, press H can cause Error log
2. conflict with nicer teleporter mod

**Comment by CoolLKKPS** [comment]
@MasterAli2 update this issue ticket, those issues happen when in v50

**Comment by CoolLKKPS** [comment]
[09:46:33.0193054] [Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
TeleportDecline.TeleportDeclineBase.DeclineTeleport (UnityEngine.InputSystem.InputAction+CallbackContext context) (at <65bcf3c97d3a4808b680c5ee0aeae0ef>:0)
UnityEngine.InputSystem.Utilities.DelegateHelpers.InvokeCallbacksSafe[TValue] (UnityEngine.InputSystem.Utilities.CallbackArray`1[System.Action`1[TValue]]& callbacks, TValue argument, System.String callbackName, System.Object context) (at <dbb0ce7b96144bd8bcbcb8b0d765f970>:0)
UnityEngine.Logger:LogException(Exception, Object)
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass4_0:<LogException>b__0()
AsyncLoggers.Wrappers.Unity.<>c__DisplayClass28_0:<wrapCallback>b__0()
AsyncLoggers.Wrappers.JobWrapper:LogWorker()
AsyncLoggers.Wrappers.LogJob:Execute()
Unity.Jobs.JobStruct`1:Execute(LogJob&, IntPtr, IntPtr, JobRanges&, Int32)

[09:46:33.0193054] [Error  : Unity Log] NullReferenceException while executing 'performed' callbacks of 'MasterAli2.TeleportDecline.TeleportDeclineInputClass/DeclineKey[/Keyboard/c]'

**Comment by MasterAli2** [comment]
I probably wont be fixing the conflict with nicer teleporter since it uses Transpilers. So no changes to this mod regarding the conflict will be done to this mod.
